Repository Open-Lens/lens, pull requests merged in 2024-03, with the labels that each got.

#8 fix: Infinite loop on extension install
  packages/core/src/extensions/extension-loader/extension-loader.ts
Labels: bug

#9 feat: Bump version to 6.5.3
  open-lens/package.json
  package-lock.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/extension-api/package.json
  packages/resource-templates/package.json
Labels: help wanted, chore

#11 Feat/upgrade kube
  open-lens/package.json
  package-lock.json
  packages/core/package.json
  packages/core/src/common/kube-helpers.ts
  packages/core/src/test-env/application-information-fake.injectable.ts
Labels: dependencies

#15 fix: using correct repo name for lens-k8s-proxy
  packages/ensure-binaries/src/index.ts
Labels: dependencies

#12 Support Nodejs v18
  .github/workflows/check-docs.yml
  .github/workflows/cron-test.yaml
  .github/workflows/daily-alpha.yml
  .github/workflows/electronegativity.yml
  .github/workflows/linter.yml
  .github/workflows/mkdocs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-release-npm.yml
  .github/workflows/test.yml
  README.md
  open-lens/package.json
  package-lock.json
  packages/core/package.json
  packages/core/src/main/__test__/prometheus-handler.test.ts
  packages/core/src/renderer/components/cluster/cluster-issues.tsx
Labels: dependencies

#16 feat: use repo variables for OSes in linter and integration worflows
  .github/workflows/check-docs.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cron-test.yaml
  .github/workflows/daily-alpha.yml
  .github/workflows/electronegativity.yml
  .github/workflows/license-header.yml
  .github/workflows/linter.yml
  .github/workflows/maintenance.yml
  .github/workflows/mkdocs-delete-version.yml
  .github/workflows/mkdocs-manual.yml
  .github/workflows/mkdocs-set-default-version.yml
  .github/workflows/publish-docs.yml
  .github/workflows/publish-release-npm.yml
  .github/workflows/release.yml
  .github/workflows/require-milestone.yml
  .github/workflows/require-type-labels.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  open-lens/package.json
  package-lock.json
  packages/core/package.json
Labels: enhancement

#34 fix: unicode-char in filename
  packages/core/src/features/helm-releases/renderer/request-helm-release.injectable.ts
  packages/core/src/renderer/components/helm-releases/release-details/release-details-model/request-detailed-helm-release.injectable.ts
Labels: bug

#14 Fix broken links
  README.md
  docs/README.md
  docs/extensions/capabilities/styling.md
  docs/extensions/get-started/anatomy.md
  docs/extensions/get-started/wrapping-up.md
  docs/extensions/get-started/your-first-extension.md
  docs/extensions/guides/README.md
  docs/extensions/guides/kube-object-list-layout.md
  packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/renderer/components/extensions/extensions.tsx
Labels: dependencies

#39 Added vulnerability scan with codeQL
  .github/workflows/require-type-labels.yml
  .github/workflows/scan-codeql.yml
Labels: security

#40 Revert "fix: Infinite loop on extension install"
  packages/core/src/extensions/extension-loader/extension-loader.ts
Labels: bug
